### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by a1oneee** [amirDahari1/SuperRes#19]
Traceback (most recent call last):
  File "code/Architecture.py", line 244, in <module>
    _, _, fake_for_d = generate_fake_image(detach_output=True)
  File "code/Architecture.py", line 182, in generate_fake_image
    input_to_G = BM_G.random_batch_for_fake(batch_size, g_slice)
  File "/data/run01/scz0539/hqj/SuperRes-master/SuperRes-master/code/BatchMaker.py", line 115, in random_batch_for_fake
    return self.random_batch3d(batch_size, dim_chosen)
  File "/data/run01/scz0539/hqj/SuperRes-master/SuperRes-master/code/BatchMaker.py", line 128, in random_batch3d
    res[i, ...] = self.generate_a_random_image3d(dim_chosen)
  File "/data/run01/scz0539/hqj/SuperRes-master/SuperRes-master/code/BatchMaker.py", line 140, in generate_a_random_image3d
    s_ind = np.random.randint(np.array(self.im.shape[1:]) - h_r)
  File "mtrand.pyx", line 985, in mtrand.RandomState.randint
TypeError: only size-1 arrays can be converted to Python scalars

**Comment by amirDahari1** [comment]
Hi @a1oneee and thanks for posting an issue! 
I can't reproduce your issue, but I think this is because you are using an [old version](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html) of numpy, in which np.random.randint cannot recieve an [array like of ints](https://numpy.org/devdocs/reference/random/generated/numpy.random.randint.html) as a parameter in 'low'. 
Try upgrading numpy to a version > 1.17
